### PR TITLE
Add configuration for CI: Travis-CI and AppVeyor

### PR DESCRIPTION
**Pull request by awwad**
The addition of these simple .travis.yml and appveyor.yml files here configures Travis-CI and AppVeyor to run automated tests for each push to the repository.

An explanation of CI setup and configuration is currently available [here](https://github.com/SeattleTestbed/seattlelib_v2/wiki/Continuous-Integration-for-the-Team).

### CODE REVIEW

**Comment by awwad** [comment]
You can see the build results here: https://travis-ci.org/SeattleTestbed/seattlelib_v2
This includes a variety of failures, listed here as links to the build output with the relevant lines highlighted:

- [Running: ut_seattlelib_dylinkrepyportabilityimportmodulesymbols.py [ FAIL ]](https://travis-ci.org/SeattleTestbed/seattlelib_v2/jobs/103901701#L2616-L2620)
- [Running: ut_seattlelib_httpretrieve_content.py              [ FAIL ]](https://travis-ci.org/SeattleTestbed/seattlelib_v2/jobs/103901701#L2631-L2638)
- (excluding the other errors in that class of "'dy_import_module_symbols' is not defined")
- [Running: ut_librepy_recvmess-reuse.r2py                     [ FAIL ]](https://travis-ci.org/SeattleTestbed/seattlelib_v2/jobs/103901701#L2753-L2773)
- [Running: ut_librepy_socket-nonblocksend.r2py                [ FAIL ]](https://travis-ci.org/SeattleTestbed/seattlelib_v2/jobs/103901701#L2791-L2810)
- [Running: ut_librepy_waitforconn-reuse.r2py                  [ FAIL ]](https://travis-ci.org/SeattleTestbed/seattlelib_v2/jobs/103901701#L2834-L2853)
- [Running: ut_librepy_waitforconn-stop.r2py                   [ FAIL ]](https://travis-ci.org/SeattleTestbed/seattlelib_v2/jobs/103901701#L2860-L2879)

**Comment by awwad** [comment]
I won't go into the same amount of detail for all the other Travis-CI runs, or [the AppVeyor runs here](https://ci.appveyor.com/project/awwad/seattlelib-v2/build/1.0.7/job/modb9lo6yfwt945s), but most of them are similar.

**Comment by awwad** [comment]
Seems to be working as intended now - 3 Python versions on Linux (2.5, 2.6, 2.7), 2 on OS X (2.6, 2.7), and 2 on Windows 2012 Server RC2 (2.6, 2.7), with the Windows builds running on 32- and 64-bit architecture.

**Comment by lukpueh** [comment]
I confirm successful run of travis-CI with provided config in seattlelib_v2 master branch and test branch by pushing newly created .travis.yml to each branch respectively.  Tests ran on Linux (Python v2.7.9, v2.6.9, v2.5.6) and OS X (v2.7.5,  v2.6.9).
Results can be found on https://travis-ci.org/lukpueh/seattlelib_v2/branches

**Comment by lukpueh** [comment]
.travis.yml and .appvoyer.yml are generic for all(?) SeattleTestbed components so it would be nice to have a central SeattleTestbed/CI repo for the config files where they can be maintained and cloned from.

**Comment by awwad** [comment]
[That](https://github.com/SeattleTestbed/seattlelib_v2/pull/178#issuecomment-212015621) (central config) is a good point, Lukas. (: Maybe they can live in [SeattleTestbed/common](https://github.com/SeattleTestbed/common) or [SeattleTestbed/buildscripts](https://github.com/SeattleTestbed/buildscripts). Thoughts?

**Comment by lukpueh** [comment]
[SeattleTestbed/buildscripts](https://github.com/SeattleTestbed/buildscripts) sounds good. [SeattleTestbed/common](https://github.com/SeattleTestbed/common) as this would

**Comment by lukpueh** [comment]
Candidates and docs for this PR have moved (see SeattleTestbed/continuous-integration#2 and SeattleTestbed/docs#19). We'll address modifications there and also deploy the fresh CI configs from there. I'm closing this PR for the time being.

To be sure that we won't omit any changes, I locally compared the relevant files:
```bash
$ diff -u continuous-integration/appveyor.yml seattlelib_v2-awwad/appveyor.yml
# no output - files don't differ
$ diff -u continuous-integration/.travis.yml seattlelib_v2-awwad/.travis.yml
# no output - files don't differ
```

**Pull request closed without merging**
