### PR TITLE
Fix #170, rectify `argparse.r2py`

### LINKED ISSUE #170: misuse of callargs in argparse.r2py
Both argparse_scan_str and argparse_scan_int use callargs and args_array inconsistently. For example, https://github.com/SeattleTestbed/seattlelib_v2/blob/master/argparse.r2py#L101-L112 and https://github.com/SeattleTestbed/seattlelib_v2/blob/master/argparse.r2py#L156-L173

As a result, this messes up callargs as a global variable. When argparse.r2py is used, "global name 'callargs' is not defined" is thrown.

### PR DESCRIPTION
**Pull request by aaaaalbert**
Also, add unit tests.

### CODE REVIEW

**Comment by aaaaalbert** [comment]
@yyzhuang, feel free to test this version of `argparse` for your project.

----
Unit test results from my humble machine:

```
albert$ for FILE in *_argparse_* ; do python utf.py -f $FILE ; done
Testing module: seattlelib
	Running: ut_seattlelib_argparse_scan_bool.r2py              [ PASS ]
Testing module: seattlelib
	Running: ut_seattlelib_argparse_scan_bool_default.r2py      [ PASS ]
Testing module: seattlelib
	Running: ut_seattlelib_argparse_scan_bool_missing.r2py      [ PASS ]
Testing module: seattlelib
	Running: ut_seattlelib_argparse_scan_int.r2py               [ PASS ]
Testing module: seattlelib
	Running: ut_seattlelib_argparse_scan_int_default.r2py       [ PASS ]
Testing module: seattlelib
	Running: ut_seattlelib_argparse_scan_int_missing.r2py       [ PASS ]
Testing module: seattlelib
	Running: ut_seattlelib_argparse_scan_int_missing_value.r2py [ PASS ]
Testing module: seattlelib
	Running: ut_seattlelib_argparse_scan_int_nonint.r2py        [ PASS ]
Testing module: seattlelib
	Running: ut_seattlelib_argparse_scan_int_uses_first.r2py    [ PASS ]
Testing module: seattlelib
	Running: ut_seattlelib_argparse_scan_str.r2py               [ PASS ]
Testing module: seattlelib
	Running: ut_seattlelib_argparse_scan_str_default.r2py       [ PASS ]
Testing module: seattlelib
	Running: ut_seattlelib_argparse_scan_str_missing.r2py       [ PASS ]
Testing module: seattlelib
	Running: ut_seattlelib_argparse_scan_str_missing_value.r2py [ PASS ]
Testing module: seattlelib
	Running: ut_seattlelib_argparse_scan_str_uses_first.r2py    [ PASS ]
```

**Comment by XuefengHuang** [comment]
I think we also need a unit test to check whether `argparse_scan_str` can parse non-str value of str argument, just like `ut_seattlelib_argparse_scan_int_nonint.r2py`

**Comment by aaaaalbert** [comment]
Hmmm, the point is that all callargs are `str`s in the first place (and are not parsed into `str`). Parsing from `str` is only done for `int` args.

Example: `123` is a string that can be parsed as an integer. `xyz` is a string that cannot be parsed as an integer. (Both are strings, still).

**Comment by XuefengHuang** [comment]
OK, that makes sense to me!

**Pull request merged**
